### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by cknost**

### CODE REVIEW

**Comment by pwqw** [comment]
First of all thank you for the updates.

Regarding this commit, I prefer `openjdk8` instead of `oraclejdk8`. Or at most both, with a OR condition if possible.

**Comment by cknost** [comment]
okay, i will change it to openjdk8.
The orginal Plugin use oraclejdk8.

**Comment by cknost** [comment]
The Plugin don't work with my Xiaomi Mi a2 and android 9.
Cordova 7.1.4.
I can't find the reason. I can't listen to Music.

**Comment by cknost** [comment]
The cordova-plugin-media works.

**Comment by pwqw** [comment]
well, this version needs a complete update, and a comparison with `cordova-plugin-media`.

Also, try if native android and `cordova-plugin-media` already play aac internally. I heard that the aac decoder was incorporated into the android core.

Regarding this pull request, I do not think all those YAML configurations are necessary, but welcome.

**Pull request merged**
